name: Automated Daily Push

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "Rohith Reddy Depa"
          git config --global user.email "rohithreddydepa@gmail.com"

      - name: Update file and commit
        run: |
          echo "Last updated: $(date)" >> daily-update.txt
          git add daily-update.txt
          # Commit only if there are changes
          git diff --cached --quiet || git commit -m "Automated update"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git HEAD:main
